[theme]
primaryColor = "#004DC1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#343A40"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
